language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "v4.0.0"
  - "iojs"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install: npm install -g grunt-cli
